use camino::{Utf8Path, Utf8PathBuf};
use monad_config::{default_manifest, write_manifest};
use monad_core::{CommandOutcome, Finding};

#[derive(Debug, thiserror::Error)]
pub enum GeneratorError {
#[error("I/O error: {0}")]
Io(#[from] std::io::Error),

```
#[error("configuration error: {0}")]
Config(#[from] monad_config::ConfigError),
```

}

pub fn new_workspace(
root: &Utf8Path,
name: &str,
dry_run: bool,
) -> Result<CommandOutcome, GeneratorError> {
let target = root.join(name);

```
if dry_run {
    return Ok(CommandOutcome::ok(
        "new",
        format!("Would create workspace at {target}"),
    ));
}

create_workspace_dirs(&target)?;
write_workspace_files(&target, name)?;

Ok(CommandOutcome::changed(
    "new",
    format!("Created workspace scaffold at {target}"),
))
```

}

pub fn init_workspace(root: &Utf8Path, dry_run: bool) -> Result<CommandOutcome, GeneratorError> {
let name = root
.file_name()
.map(ToOwned::to_owned)
.unwrap_or_else(|| "monad-workspace".to_string());

```
if dry_run {
    return Ok(CommandOutcome::ok(
        "init",
        format!("Would initialize Monad workspace in {root}"),
    ));
}

create_workspace_dirs(root)?;
write_workspace_files(root, &name)?;

Ok(CommandOutcome::changed(
    "init",
    format!("Initialized Monad workspace in {root}"),
))
```

}

pub fn add_stub(
root: &Utf8Path,
kind: &str,
name: &str,
dry_run: bool,
) -> Result<CommandOutcome, GeneratorError> {
let base_dir = match kind {
"app" | "apps" => "apps",
"service" | "services" => "services",
"package" | "packages" => "packages",
"lib" | "libs" | "library" => "libs",
"cli" | "tool" | "tools" => "tools",
"worker" | "job" | "function" => "services",
"docs" | "doc" => "docs",
"infra" => "infra",
other => other,
};

```
let target = root.join(base_dir).join(name);

if dry_run {
    return Ok(CommandOutcome::ok(
        "add",
        format!("Would add {kind} `{name}` at {target}"),
    ));
}

fs_err::create_dir_all(target.join("src"))?;
fs_err::write(
    target.join("README.md"),
    format!(
        "# {name}\n\nGenerated `{kind}` stub.\n\n## Next steps\n\n- Add implementation.\n- Add tests.\n- Wire into CI/task graph.\n"
    ),
)?;
fs_err::write(
    target.join(".gitkeep"),
    "",
)?;
fs_err::write(
    target.join("src").join(".gitkeep"),
    "",
)?;

Ok(CommandOutcome::changed(
    "add",
    format!("Added {kind} `{name}` at {target}"),
)
.with_finding(Finding::info(
    "stub.created",
    "This is a structural stub. Runtime-specific files can be generated by a later command.",
)))
```

}

fn create_workspace_dirs(root: &Utf8Path) -> Result<(), GeneratorError> {
for dir in [
"apps",
"services",
"packages",
"libs",
"tools",
"infra",
"docs",
"contracts",
"policies",
"scripts",
".github/workflows",
] {
fs_err::create_dir_all(root.join(dir))?;
}

```
Ok(())
```

}

fn write_workspace_files(root: &Utf8Path, name: &str) -> Result<(), GeneratorError> {
write_manifest(root, &default_manifest(name))?;

```
fs_err::write(
    root.join("README.md"),
    format!(
        "# {name}\n\nGenerated by Monad.\n\n## Layout\n\n- `apps/`\n- `services/`\n- `packages/`\n- `libs/`\n- `tools/`\n- `infra/`\n- `docs/`\n- `contracts/`\n- `policies/`\n"
    ),
)?;

fs_err::write(
    root.join(".gitignore"),
    "/node_modules\n/target\n/.monad\n.env\n.env.*\n!.env.example\n",
)?;

fs_err::write(root.join("apps").join(".gitkeep"), "")?;
fs_err::write(root.join("services").join(".gitkeep"), "")?;
fs_err::write(root.join("packages").join(".gitkeep"), "")?;
fs_err::write(root.join("libs").join(".gitkeep"), "")?;
fs_err::write(root.join("tools").join(".gitkeep"), "")?;
fs_err::write(root.join("infra").join(".gitkeep"), "")?;
fs_err::write(root.join("docs").join(".gitkeep"), "")?;

Ok(())
```

}

pub fn current_dir_utf8() -> Utf8PathBuf {
let cwd = std::env::current_dir().expect("current directory should be available");
Utf8PathBuf::from_path_buf(cwd).expect("current directory should be valid UTF-8")
}
