pub const WORKSPACE_README: &str = r#"# {{name}}

Generated by Monad.

## Layout

* `apps/` - deployable applications
* `services/` - backend services and workers
* `packages/` - shared packages
* `libs/` - shared libraries
* `infra/` - infrastructure
* `docs/` - documentation
  "#;

pub const PROJECT_README: &str = r#"# {{name}}

Generated project stub.

## Next steps

1. Choose runtime/framework.
2. Add dependencies.
3. Add tests.
4. Wire into task graph.
5. Wire into CI.
   "#;
